// Optional isolated-browser regression; run against the local preview on port 8000.
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const context=await browser.newContext({serviceWorkers:'allow'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const result={results:[{kind:'podcast',collectionId:123,collectionName:'Example Podcast',artistName:'Example Publisher',feedUrl:'https://example.com/feed.xml',genres:['Technology','Podcasts']}]};
  await context.route('https://api.podcastindex.org/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(result)}));
  const xml='<?xml version="1.0"?><rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:podcast="https://podcastindex.org/namespace/1.0"><channel><title>Example Podcast</title><link>https://example.com/</link><itunes:complete>yes</itunes:complete><itunes:category text="Technology"><itunes:category text="Software"/></itunes:category><podcast:funding url="https://example.com/support">Support us</podcast:funding>'+[1,2,3,4].map(i=>'<item><guid>'+i+'</guid><pubDate>'+new Date(Date.now()-i*7*86400000).toUTCString()+'</pubDate><itunes:duration>30:00</itunes:duration></item>').join('')+'</channel></rss>';
  await context.route('https://example.com/feed.xml',route=>route.fulfill({contentType:'application/xml',body:xml}));
  await page.goto(process.env.PODCAST_TEST_URL||'http://127.0.0.1:8000');await page.waitForSelector('html.app-ready');await page.keyboard.press('4');await page.locator('#podcastsWorkspace').waitFor({state:'visible'});
  // Name-adjacent search uses the typed title; feed refresh populates automatic controls.
  await page.locator('#podcastsAdd').click();await page.locator('#podcastNameSearch').click();assert.match(await page.locator('#podcastEditorStatus').innerText(),/Enter a podcast name/);await page.locator('#podcast-title').fill('Example Podcast');await page.locator('#podcastNameSearch').click();await page.locator('[data-podcast-match]').first().waitFor();assert.equal(await page.locator('#podcastQuery').inputValue(),'Example Podcast');await page.locator('[data-podcast-match]').first().click();await page.locator('#podcastRefresh').click();await page.waitForFunction(()=>document.querySelector('#podcastEditorStatus').textContent.includes('refreshed'));assert.equal(await page.locator('#podcast-activity').inputValue(),'Inactive');assert.equal(await page.locator('#podcast-size').inputValue(),'M');assert.equal(await page.locator('#podcast-frequency').inputValue(),'Weekly');assert.equal(await page.locator('#podcast-website').inputValue(),'https://example.com/');
  await page.locator('#podcast-frequency').selectOption('Daily');await page.locator('#podcastRefresh').click();await page.waitForFunction(()=>document.querySelector('#podcastEditorStatus').textContent.includes('refreshed'));assert.equal(await page.locator('#podcast-frequency').inputValue(),'Daily');await page.locator('#podcast-frequency').selectOption('Unknown');assert.equal(await page.locator('#podcast-frequency').inputValue(),'Weekly');await page.locator('#podcastCancel').click();await page.locator('#confirmDialog').getByRole('button',{name:'Discard',exact:true}).click();assert.equal(await page.locator('#podcastsRows tr').count(),0);
  const table='Name\tActive\tLast\tLen.\tRecurrence\tTime\tCategory\tSub-Categories\tCost\tMembership\tURL\nExample Podcast\tTRUE\t06/30/23\tL\tWeekly\t4\tPersonal\tDesign\t50\tPremium\thttps://example.com/\nStopped Example\tFALSE\t\tS\tMonthly\t\tSocial\t\t\t\t';
  await page.evaluate(()=>window.LocalApp.components.openDialog('#podcastImportDialog',{focus:'#podcastImportFile'}));await page.getByText('Paste the Original Table',{exact:true}).click();await page.locator('#podcastImportText').fill(table);await page.locator('#podcastImportPreview').click();assert.equal(await page.locator('#podcastImportRows tr').count(),2);
  await page.locator('[data-import-search]').first().click();await page.locator('[data-import-match]').first().waitFor();await page.locator('[data-import-match]').first().selectOption('0');
  await page.locator('#podcastImportApply').click();await page.locator('#podcastImportDialog').waitFor({state:'hidden'});assert.equal(await page.locator('#podcastsRows tr').count(),2);assert.equal(await page.locator('[data-podcast-total="listening"]').innerText(),'Listening: 1');
  await page.locator('.podcasts-filter-disclosure summary').click();await page.locator('#podcastsStatus').selectOption('Stopped');assert.equal(await page.locator('#podcastsRows tr').count(),1);assert.equal(await page.locator('[data-podcast-total="listening"]').innerText(),'Listening: 0');await page.locator('#podcastsStatus').selectOption('all');
  // TV-style compact list, inline edits, search shortcut and personal-rating pivots.
  await page.keyboard.press('.');assert.equal(await page.locator('#podcastsSearch').evaluate(e=>document.activeElement===e),true);await page.locator('#podcastsSearch').fill('Stopped');assert.equal(await page.locator('#podcastsCount').innerText(),'1 / 2 entries');await page.locator('#podcastsSearch').fill('');
  const first=page.locator('#podcastsRows tr').first();assert.equal(await first.locator('.podcast-linked').count(),1);assert.equal(await first.locator('[data-column="cost"]').innerText(),'$50');assert.equal(await first.locator('[data-column="membership"]').innerText(),'Premium');
  await first.locator('[data-podcast-edit="rating"]').selectOption('5');await page.waitForFunction(()=>window.LocalApp.storage.getState().workspace.podcasts[0].rating===5);
  await first.locator('[data-podcast-edit="status"]').selectOption('Stopped');await page.waitForFunction(()=>window.LocalApp.storage.getState().workspace.podcasts[0].status==='Stopped');assert.match(await first.locator('[data-podcast-edit="status"]').getAttribute('class'),/red/);
  await first.locator('[data-podcast-edit="status"]').selectOption('Listening');await page.waitForFunction(()=>window.LocalApp.storage.getState().workspace.podcasts[0].status==='Listening');
  assert.ok(await first.evaluate(e=>e.getBoundingClientRect().height)<=36,'Rows should stay compact like TV');
  await page.locator('[data-podcasts-view="pivots"]').click();assert.equal(await page.locator('#podcastsPivotCards .pivot-card').count(),7);const personal=page.locator('[data-podcast-pivot="category"][data-value="Personal"]');assert.match(await personal.locator('xpath=ancestor::tr').innerText(),/5.0/);
  await page.locator('#podcastsPivotSearch').fill('personal');assert.equal(await page.locator('[data-podcast-pivot]').count(),1);await page.locator('#podcastsPivotSearch').fill('');await page.locator('#podcastsPivotMin').fill('2');await page.locator('#podcastsPivotMin').press('Tab');assert.equal(await page.locator('[data-podcast-pivot="category"]').count(),0);await page.locator('#podcastsPivotMin').fill('1');await page.locator('#podcastsPivotMin').press('Tab');
  await page.locator('#podcastsPivotSort').selectOption('average');await personal.click();assert.equal(await page.locator('#podcastsRows tr').count(),1);await page.locator('#podcastsClear').click();assert.equal(await page.locator('#podcastsRows tr').count(),2);
  await page.getByRole('button',{name:'Example Podcast',exact:true}).click();await page.locator('#podcastRefresh').click();await page.waitForFunction(()=>document.querySelector('#podcastEditorStatus').textContent.includes('refreshed'));
  // Catalog identity/facts lead the compact desktop editor; every dropdown shares one column.
  assert.equal(await page.evaluate(()=>document.querySelector('#podcastLinked').getBoundingClientRect().top<document.querySelector('#podcast-title').getBoundingClientRect().top),true);
  const selectRects=await page.locator('#podcastDialog select').evaluateAll(nodes=>nodes.map(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,width:e.getBoundingClientRect().width})));
  assert.equal(selectRects.length,7);assert.ok(selectRects.every((r,i)=>Math.abs(r.x-selectRects[0].x)<1&&Math.abs(r.width-selectRects[0].width)<1&&(i===0||r.y>selectRects[i-1].y)));
  await page.locator('[data-podcast-rating="4"]').click();assert.equal(await page.locator('#podcast-rating').inputValue(),'4');assert.equal(await page.locator('[data-podcast-rating="4"]').getAttribute('aria-pressed'),'true');await page.locator('[data-podcast-rating="4"]').click();assert.equal(await page.locator('#podcast-rating').inputValue(),'');await page.locator('[data-podcast-rating="5"]').click();
  assert.equal(await page.locator('#podcast-size').inputValue(),'L');assert.equal(await page.locator('#podcast-member-amount').inputValue(),'50');assert.match(await page.locator('#podcastFacts').innerText(),/30 min from 4 episodes/);await page.locator('#podcastSave').click();await page.locator('#podcastDialog').waitFor({state:'hidden'});
  assert.match(await page.locator('#podcastsRows tr').first().locator('[data-column="activity"]').getAttribute('class'),/purple/);assert.equal(await page.locator('#podcastFacts > div').filter({hasText:'Publisher'}).locator('dd').innerText(),'Example Publisher');
  assert.match(await page.locator('#podcastsRows').innerText(),/Inactive/);assert.match(await page.locator('#podcastsRows').innerText(),/Personal/);
  assert.equal(await page.locator('#podcastsTable thead th').count(),12);const enriched=page.locator('#podcastsRows tr').first();assert.equal(await enriched.locator('[data-column="categories"]').innerText(),'Personal > Design, Software');assert.equal(await enriched.locator('[data-column="weeklyTime"]').innerText(),'0.5 hr');assert.equal(await page.locator('[data-podcast-total="weeklyTime"]').innerText(),'Total: 0.5 hr');assert.match(await page.locator('[data-podcast-total="weeklyTime"]').getAttribute('title'),/1 unknown excluded/);
  assert.equal(await enriched.locator('[data-column="website"] svg').count(),1);
  await page.locator('[data-podcast-resize="rating"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>window.LocalApp.storage.getState().ui.podcasts.widths.rating),80);
  const resize=page.locator('[data-podcast-resize="categories"]'),box=await resize.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2);await page.mouse.up();assert.equal(await page.evaluate(()=>window.LocalApp.storage.getState().ui.podcasts.widths.categories),260);
  await page.locator('#podcastsRefresh').click();await page.waitForFunction(()=>!document.querySelector('#podcastsRefresh').disabled);assert.doesNotMatch(await page.locator('#podcastsRefresh').innerText(),/Never updated/);assert.equal(await page.locator('#podcastsRefresh br').count(),0);assert.equal(await page.locator('#podcastsImport').count(),0);assert.equal(await page.locator('#podcastsAdd .button-label').innerText(),'Add');assert.equal(await enriched.locator('[data-column="categories"] strong').innerText(),'Software');const keys=await page.locator('#podcastsTable thead th').evaluateAll(es=>es.map(e=>e.dataset.column));assert.ok(keys.indexOf('frequency')<keys.indexOf('weeklyTime'));
  assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#podcastsTable thead th')).position),'sticky');
  await page.locator('#podcastsListView .podcast-scroll').evaluate(e=>e.scrollLeft=e.scrollWidth);assert.equal(await enriched.locator('[data-column="website"]').isVisible(),true);await page.locator('#podcastsListView .podcast-scroll').evaluate(e=>e.scrollLeft=0);
  const saved=await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts);
  assert.equal(saved[0].catalog.appleId,'123');assert.equal(saved[0].activity,'Unknown');assert.equal(saved[0].catalog.activity,'Inactive');assert.equal(saved[0].catalog.fundingUrl,'https://example.com/support');assert.equal(saved[0].membership.available,'Yes');assert.equal(saved[0].legacy.last,'06/30/23');
  // Feed parser rejects DTD/entities and XML parser errors; funding never means membership.
  assert.equal(await page.evaluate(()=>{try{window.LocalApp.podcastFeed.parse('<!DOCTYPE rss [<!ENTITY x SYSTEM "file:///etc/passwd">]><rss/>');return false;}catch{return true;}}),true);
  assert.equal(await page.evaluate(()=>{try{window.LocalApp.podcastFeed.parse('<rss><channel>');return false;}catch{return true;}}),true);
  // Reimport keeps personal edits and skips already linked rows without duplication.
  await page.getByRole('button',{name:'Example Podcast',exact:true}).click();await page.locator('#podcast-title').fill('My Edited Podcast');await page.locator('#podcastSave').click();await page.locator('#podcastDialog').waitFor({state:'hidden'});
  await page.evaluate(()=>window.LocalApp.components.openDialog('#podcastImportDialog',{focus:'#podcastImportFile'}));await page.locator('#podcastImportText').fill(table);await page.locator('#podcastImportPreview').click();assert.match(await page.locator('#podcastImportRows').innerText(),/Already linked/);assert.equal(await page.locator('#podcastImportApply').isDisabled(),true);await page.locator('#podcastImportDialog [data-close-dialog]').last().click();
  // A stale editor cannot overwrite an intervening mutation.
  await page.getByRole('button',{name:'My Edited Podcast',exact:true}).click();await page.locator('#podcast-title').fill('Stale draft');await page.evaluate(()=>window.LocalApp.storage.mutate(s=>{s.workspace.podcasts[0].status='Stopped';},{reason:'test-concurrent-edit'}));await page.locator('#podcastSave').click();assert.match(await page.locator('#podcastEditorStatus').innerText(),/changed/);await page.locator('#podcastCancel').click();await page.locator('#confirmDialog').getByRole('button',{name:'Discard',exact:true}).click();
  // Failed storage writes preserve live state and the editor draft.
  await page.getByRole('button',{name:'My Edited Podcast',exact:true}).click();await page.locator('#podcast-title').fill('Unsaved name');await page.evaluate(()=>{window.podcastTestSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key===window.LocalApp.config.storage.stateKey)throw new DOMException('Quota','QuotaExceededError');return window.podcastTestSetItem.call(this,key,value);};});await page.locator('#podcastSave').click();assert.equal(await page.locator('#podcastDialog').isVisible(),true);assert.match(await page.locator('#podcastEditorStatus').innerText(),/could not fit|Could not save/);assert.equal(await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts[0].title),'My Edited Podcast');await page.evaluate(()=>{Storage.prototype.setItem=window.podcastTestSetItem;delete window.podcastTestSetItem;});await page.locator('#podcastCancel').click();await page.locator('#confirmDialog').getByRole('button',{name:'Discard',exact:true}).click();
  // Full backup, content sync, and offline shell preserve data and local controls.
  const roundtrip=await page.evaluate(()=>{const a=window.LocalApp,s=a.storage.getState();return {backup:a.stateModel.prepare(a.stateModel.exportEnvelope(s)).state.workspace.podcasts,cloud:a.stateModel.prepareSync(a.stateModel.syncPayload(s)).state.workspace.podcasts};});assert.equal(roundtrip.backup.length,2);assert.equal(roundtrip.backup[0].rating,5);assert.deepEqual(roundtrip.backup.sort((a,b)=>a.id.localeCompare(b.id)),roundtrip.cloud.sort((a,b)=>a.id.localeCompare(b.id)));
  if(await page.getByRole('button',{name:'Dismiss notification',exact:true}).isVisible())await page.getByRole('button',{name:'Dismiss notification',exact:true}).click();
  for(const width of [1280,390,320]){await page.locator('[data-podcasts-view="pivots"]').click();await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('[data-podcasts-view="list"]').click();await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'My Edited Podcast',exact:true}).click();assert.equal(await page.evaluate(()=>document.querySelector('#podcastDialog').getBoundingClientRect().width<=innerWidth),true);await page.locator('#podcastCancel').click();}
  await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForSelector('html.app-ready');await context.setOffline(true);await page.reload();await page.waitForSelector('html.app-ready');await page.getByRole('button',{name:'My Edited Podcast',exact:true}).click();await page.locator('#podcast-status').selectOption('Listening');await page.locator('#podcastSave').click();await page.locator('#podcastDialog').waitFor({state:'hidden'});await page.reload();await page.waitForSelector('html.app-ready');assert.equal(await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts[0].status),'Listening');await context.setOffline(false);
  // Feed access errors explain browser restrictions; malformed XML retains its own diagnosis.
  await context.unroute('https://example.com/feed.xml');await context.route('https://example.com/feed.xml',route=>route.abort('failed'));
  const priorFeed=await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts[0].catalog);
  await page.getByRole('button',{name:'My Edited Podcast',exact:true}).click();await page.locator('#podcastRefresh').click();await page.waitForFunction(()=>document.querySelector('#podcastEditorStatus').textContent.includes('CORS'));assert.match(await page.locator('#podcastEditorStatus').innerText(),/Saved feed details are kept/);assert.deepEqual(await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts[0].catalog),priorFeed);
  await page.locator('.podcast-feed-tools summary').click();assert.equal(await page.locator('#podcastFeedOpen').getAttribute('href'),'https://example.com/feed.xml');assert.equal(await page.locator('#podcastFeedOpen').isVisible(),true);
  await context.unroute('https://example.com/feed.xml');await context.route('https://example.com/feed.xml',route=>route.fulfill({contentType:'application/xml',body:'<rss>'}));await page.locator('#podcastRefresh').click();await page.waitForFunction(()=>document.querySelector('#podcastEditorStatus').textContent.includes('Invalid RSS XML'));assert.doesNotMatch(await page.locator('#podcastEditorStatus').innerText(),/CORS|browser access is blocked/);await page.locator('#podcastCancel').click();
  // Delete saves recovery before replacing the row with a tombstone.
  await page.getByRole('button',{name:'Stopped Example',exact:true}).click();await page.locator('#podcastDelete').click();await page.locator('#confirmDialog').getByRole('button',{name:'Delete',exact:true}).click();await page.locator('#podcastDialog').waitFor({state:'hidden'});assert.equal(await page.locator('#podcastsRows tr').count(),1);assert.equal(await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts.find(p=>p.id.includes('table')&&p.deleted)?.deleted),true);
  // Bulk refresh reports each result live and persists success/new failure/retained-success colors.
  await page.evaluate(()=>{const a=window.LocalApp;a.storage.mutate(s=>{s.workspace.podcasts=[a.podcasts.normalize({id:'color-success',title:'The Alpha',catalog:{feedUrl:'https://example.com/good.xml'}}),a.podcasts.normalize({id:'color-failed',title:'Beta',catalog:{feedUrl:'https://example.com/new-failure.xml'}}),a.podcasts.normalize({id:'color-warning',title:'The Gamma',catalog:{feedUrl:'https://example.com/old-failure.xml',feedFetchedAt:'2026-10-01T12:00:00Z'}})];s.ui.podcasts.sort='title';s.ui.podcasts.direction='asc';},{reason:'test'});a.podcastFeed.refresh=async c=>{await new Promise(resolve=>setTimeout(resolve,c.feedUrl.includes('old-failure')?400:50));if(c.feedUrl.includes('failure'))throw new Error('Test feed unavailable');return {...c,feedFetchedAt:new Date().toISOString()};};});
  assert.deepEqual(await page.locator('#podcastsRows .podcast-name').allTextContents(),['The Alpha','Beta','The Gamma']);
  await page.locator('#podcastsRefresh').click();await page.waitForSelector('[data-podcast-id="color-success"] .podcast-refresh-success');assert.equal(await page.locator('#podcastsRefresh').isDisabled(),true);await page.waitForFunction(()=>!document.querySelector('#podcastsRefresh').disabled);
  assert.equal(await page.locator('[data-podcast-id="color-failed"] .podcast-refresh-failed').count(),1);assert.equal(await page.locator('[data-podcast-id="color-warning"] .podcast-refresh-warning').count(),1);assert.match(await page.locator('[data-podcast-id="color-warning"] .podcast-linked').getAttribute('aria-label'),/previous successful feed/);
  await page.reload();await page.waitForSelector('html.app-ready');assert.equal(await page.locator('.podcast-refresh-success').count(),1);assert.equal(await page.locator('.podcast-refresh-failed').count(),1);assert.equal(await page.locator('.podcast-refresh-warning').count(),1);
  const beforeStoppedBatch=await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts);
  await page.evaluate(()=>{window.LocalApp.podcastFeed.refresh=async c=>{await new Promise(resolve=>setTimeout(resolve,c.feedUrl.includes('old-failure')?400:50));return {...c,feedFetchedAt:new Date().toISOString()};};});await page.locator('#podcastsRefresh').click();await page.waitForSelector('[data-podcast-id="color-failed"] .podcast-refresh-success');await page.locator('#podcastsRefreshStop').click();await page.waitForFunction(()=>!document.querySelector('#podcastsRefresh').disabled);assert.equal(await page.locator('[data-podcast-id="color-failed"] .podcast-refresh-failed').count(),1);assert.equal(await page.locator('[data-podcast-id="color-warning"] .podcast-refresh-warning').count(),1);assert.deepEqual(await page.evaluate(()=>window.LocalApp.storage.getState().workspace.podcasts),beforeStoppedBatch);
  assert.deepEqual(errors,[]);console.log('Podcasts browser checks passed: list/pivots, search shortcut/counts, inline ratings/status, compact rows, catalog-first aligned modal, rating toggles, complete table columns, import/link, refresh, repeat import, stale edits, failed writes, backup/sync, desktop/390/320px, offline edit/reload and recovery deletion.');
  if(process.env.PODCAST_SCREENSHOT)await page.screenshot({path:process.env.PODCAST_SCREENSHOT,fullPage:true});
  await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
